import unittest
class Testudomain_exceptions:
    def test_placeholder(self):
        assert True
